// Qwik/poke-qwik/src/hooks/useCounter.tsx
import { $, useComputed$, useSignal } from "@builder.io/qwik";

export interface options {
  minValue?: number;
  maxValue?: number;
}

export const useCounter = (
  initialValue: number = 0,
  { minValue = 0, maxValue = Number.MAX_SAFE_INTEGER }: options
) => {
  const counter = useSignal<number>(initialValue);

  const decrement = $((step: number = 1) => {
    if (counter.value - step < minValue) return;
    counter.value = counter.value - step;
  });

  const increment = $((step: number = 1) => {
    if (counter.value + step > maxValue) return;
    counter.value = counter.value + step;
  });

  return {
    counter: useComputed$(() => counter.value),
    decrement,
    increment,
  };
};

// React/04_Hooks_App/src/hooks/useCounter.js
import { useState } from 'react';

export const useCounter = ( initialValue = 0, minValue = -100, maxValue = 100 ) => {
    const [ counter, setCounter ] = useState( initialValue );
    const decrement = ( value = 1 ) => {
        if( ( counter - value ) >= minValue ) setCounter( ( currentValue ) => currentValue - value );
    };
    const reset = () => setCounter( initialValue );
    const increment = ( value = 1 ) => {
        if( ( counter + value ) <= maxValue ) setCounter( ( currentValue ) => currentValue + value );
    };

    return { 
        counter,
        decrement,
        reset,
        increment
    };
};
